changelog:
  exclude:
    labels:
      - ignore-for-release

  categories:
    - title: "✨ 新增功能（New Features）"
      labels:
        - feature
        - enhancement

    - title: "🐛 问题修复（Bug Fixes）"
      labels:
        - bug
        - fix

    - title: "🛠️ 工程与维护（maintenance）"
      labels:
        - dependencies
        - ci
        - documentation
        - refactor

    - title: "📦 其他变更（Other Changes）"
      labels:
        - "*"
