[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "chromadb>=1.5.5",
    "fastapi[standard]>=0.135.3",
    "google-genai>=1.70.0",
    "httpx>=0.28.1",
    "langchain-text-splitters>=1.1.1",
    "loguru>=0.7.3",
    "openai>=2.30.0",
    "pwdlib[argon2]>=0.3.0",
    "pydantic-ai>=1.77.0",
    "pydantic-extra-types==2.11.1",
    "pydantic-settings>=2.13.1",
    "pyjwt>=2.12.1",
    "sqlalchemy>=2.0.49",
    "tokenizer>=3.6.2",
    "tree-sitter>=0.25.2",
    "tree-sitter-python>=0.25.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.pytest]
asyncio_mode = "auto"
