"""Initial schema

Revision ID: 44e7c375d999
Revises: 
Create Date: 2026-06-25 23:21:03.265845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e7c375d999'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_uid'), ['uid'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_uid'), ['uid'], unique=True)

    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('encrypted_api_key', sa.String(), nullable=True),
    sa.Column('extra_config', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_providers_uid'), ['uid'], unique=True)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('collection_name', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('LOCAL_FILE', 'WEB_CRAWL', 'GITHUB_REPO', 'CUSTOM_CONTENT', name='sourcetype'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('web_crawl_config', sa.JSON(), nullable=True),
    sa.Column('sync_interval', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAUSE_REQUESTED', 'PAUSED', 'COMPLETED', 'FAILED', name='sourceprocessstatus'), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_name'),
    sa.UniqueConstraint('source_name')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_uid'), ['uid'], unique=True)

    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('owner_type', sa.Enum('ADMIN', 'VISITOR', name='chatsessiontype'), nullable=False),
    sa.Column('visitor_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_chat_sessions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_uid'), ['uid'], unique=True)

    op.create_table('model_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('context_window_tokens', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('supports_stream', sa.Boolean(), nullable=False),
    sa.Column('supports_structured', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_model_profiles_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model', name='_provider_model_uc')
    )
    with op.batch_alter_table('model_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_profiles_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_profiles_uid'), ['uid'], unique=True)

    op.create_table('project_source_links',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_source_links_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_project_source_links_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'source_id')
    )
    op.create_table('project_widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('site_origin', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('widget_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_widgets_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='_project_widget_name_uc')
    )
    with op.batch_alter_table('project_widgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_widgets_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_widgets_site_origin'), ['site_origin'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_widgets_uid'), ['uid'], unique=True)

    op.create_table('source_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('item_key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('origin_url', sa.String(), nullable=True),
    sa.Column('item_hash', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAUSE_REQUESTED', 'PAUSED', 'COMPLETED', 'FAILED', name='sourceitemprocessstatus'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_items_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key', 'source_id', name='_item_source_uc')
    )
    with op.batch_alter_table('source_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_items_uid'), ['uid'], unique=True)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='chatmessagerole'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('MESSAGE', 'COMPACTION', name='chatmessagetype'), nullable=False),
    sa.Column('tail_start_sequence', sa.Integer(), nullable=True),
    sa.Column('rag_snapshot', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_chat_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_session_id', 'sequence', name='_session_sequence_uc')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_uid'), ['uid'], unique=True)

    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_hash', sa.String(), nullable=False),
    sa.Column('chunk_content', sa.String(), nullable=False),
    sa.Column('chunk_tokens', sa.String(), nullable=False),
    sa.Column('chunk_pos', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_header', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], name=op.f('fk_document_chunks_source_item_id_source_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_vector_id'), ['vector_id'], unique=True)

    op.create_table('document_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], name=op.f('fk_document_contents_source_item_id_source_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_rag_enabled', sa.Boolean(), nullable=False),
    sa.Column('visitor_system_prompt', sa.String(), nullable=True),
    sa.Column('visitor_max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('visitor_temperature', sa.Float(), nullable=False),
    sa.Column('visitor_top_p', sa.Float(), nullable=False),
    sa.Column('visitor_timeout', sa.Float(), nullable=False),
    sa.Column('visitor_thinking', sa.JSON(), nullable=False),
    sa.Column('rag_mode', sa.Enum('FAST', 'ADAPTIVE', 'FULL', name='searchmode'), nullable=False),
    sa.Column('rag_top_k', sa.Integer(), nullable=False),
    sa.Column('rag_rerank_enabled', sa.Boolean(), nullable=False),
    sa.Column('rag_fts_k', sa.Integer(), nullable=False),
    sa.Column('rag_vector_k', sa.Integer(), nullable=False),
    sa.Column('rag_rerank_k', sa.Integer(), nullable=False),
    sa.Column('rag_max_alternative_queries', sa.Integer(), nullable=False),
    sa.Column('rag_max_keywords', sa.Integer(), nullable=False),
    sa.Column('rag_standalone_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('visitor_default_provider_id', sa.Integer(), nullable=True),
    sa.Column('visitor_default_model_profile_id', sa.Integer(), nullable=True),
    sa.Column('auxiliary_model_profile_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auxiliary_model_profile_id'], ['model_profiles.id'], name=op.f('fk_project_settings_auxiliary_model_profile_id_model_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_settings_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_default_model_profile_id'], ['model_profiles.id'], name=op.f('fk_project_settings_visitor_default_model_profile_id_model_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_default_provider_id'], ['providers.id'], name=op.f('fk_project_settings_visitor_default_provider_id_providers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_settings_project_id'), ['project_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_settings_project_id'))

    op.drop_table('project_settings')
    op.drop_table('document_contents')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_vector_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_uid'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('source_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_items_uid'))

    op.drop_table('source_items')
    with op.batch_alter_table('project_widgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_widgets_uid'))
        batch_op.drop_index(batch_op.f('ix_project_widgets_site_origin'))
        batch_op.drop_index(batch_op.f('ix_project_widgets_project_id'))

    op.drop_table('project_widgets')
    op.drop_table('project_source_links')
    with op.batch_alter_table('model_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_profiles_uid'))
        batch_op.drop_index(batch_op.f('ix_model_profiles_provider_id'))

    op.drop_table('model_profiles')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_uid'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_project_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_uid'))

    op.drop_table('sources')
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_providers_uid'))

    op.drop_table('providers')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_uid'))

    op.drop_table('projects')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_uid'))

    op.drop_table('admins')
    # ### end Alembic commands ###
