"""refactor(source): make sync_interval nullable, rename synced_at to updated_at, add next_sync_at

Revision ID: 9c334119d1f9
Revises: 44e7c375d999
Create Date: 2026-07-03 14:28:00.273934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c334119d1f9'
down_revision: Union[str, Sequence[str], None] = '44e7c375d999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('sync_interval',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('synced_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE sources SET sync_interval = 24 WHERE sync_interval IS NULL")

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('sync_interval',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('next_sync_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
