"""Added project_widgets table

Revision ID: eb591d3687f6
Revises: 
Create Date: 2026-06-25 22:26:36.471762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb591d3687f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('site_origin', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('widget_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='_project_widget_name_uc')
    )
    op.create_index(op.f('ix_project_widgets_project_id'), 'project_widgets', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_widgets_site_origin'), 'project_widgets', ['site_origin'], unique=False)
    op.create_index(op.f('ix_project_widgets_uid'), 'project_widgets', ['uid'], unique=True)
    with op.batch_alter_table('projects') as batch_op:
        batch_op.drop_column('site_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects') as batch_op:
        batch_op.add_column(sa.Column('site_url', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_project_widgets_uid'), table_name='project_widgets')
    op.drop_index(op.f('ix_project_widgets_site_origin'), table_name='project_widgets')
    op.drop_index(op.f('ix_project_widgets_project_id'), table_name='project_widgets')
    op.drop_table('project_widgets')
    # ### end Alembic commands ###
